version: '2'
services:
 flink-master:
   image: bde2020/flink-master:1.7.2-hadoop2.8
   hostname: flink-master
   container_name: flink-master
#   domainname: hadoop
#   networks:
#     - hadoop
#  environment:
#      - "constraint:node==<yourmasternode>"
   ports:
     - "8080:8080"
     - "8081:8081"

 flink-worker:
   image: bde2020/flink-worker:1.7.2-hadoop2.8
   hostname: flink-worker
   container_name: flink-worker
#   domainname: hadoop
#   networks:
#     - hadoop
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
#     - FLINK_NUM_TASK_SLOTS=2
#    - "constraint:node==<yourworkernode>"
   depends_on:
      - flink-master

#networks:
#  default:
#    external:
#      name: hadoop
